### ISSUE TITLE
Help Needed: SyntaxError During Tweet Parsing on Cloudflare Deployment

### ISSUE THREAD

**Issue by Glidema** [okikio/twitter-media#4]
Hi Okiki,

I’m deploying "InThisTweet" to Cloudflare, and while most things are working fine, I’m running into an issue when trying to parse the tweet for download. The error I get is:

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON.

I’m unsure how to resolve this and would really appreciate your guidance.

Thanks a lot for your help!

**Comment by okikio** [comment]
I have a number of updates in the works for inthistweet, but unfortunately I won't be free for quite a number of months to do any work on it, I apologize.

**Comment by Glidema** [comment]
> I have a number of updates in the works for inthistweet, but unfortunately I won't be free for quite a number of months to do any work on it, I apologize.

Hi Okiki,

Thank you so much for getting back to me, and no worries at all! I completely understand that you're busy, and I appreciate the work you've already done on "InThisTweet." Whenever you do get time to update it, I’ll definitely be looking forward to it.

In the meantime, I'll see if I can explore some solutions on my own. Thanks again for your time!

Take care,

Glidema
